# Generated by Django 4.0.4 on 2022-04-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('com', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=100)),
                ('rnum', models.CharField(max_length=100)),
                ('radd', models.CharField(max_length=200)),
                ('vname', models.CharField(max_length=100)),
                ('vnum', models.CharField(max_length=100)),
                ('vadd', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='complaint',
        ),
    ]
